changehouse/urls.py
from django.urls import path, include, re_path
from changehouse.views import *
from django.contrib.auth import views as auth_views
from .views import (
    HomePageView,
    ClienteCreateView,
    ClienteListView,
    ClienteUpdateView,
    ClienteDeleteView,
    ClienteDetailView,
    CompraCreateView,
    reportView,
    LoginPageView)
from .import views

urlpatterns = [
    path('', HomePageView.as_view(), name='inicio'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('nuevo/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('listar/', ClienteListView.as_view(), name='cliente_listar'),
    path('mostrar/<int:pk>/', ClienteDetailView.as_view(), name='cliente_mostrar'),
    path('editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editar'),
    path('eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_eliminar'),
    #url('editar/(?P<pk>\d+)/$', EstudianteUpdate.as_view(), name='estudiante_editar'),
    #re_path(r'editar/(?P<pk>\d+)/$',  ClienteDeleteView.as_view(), name='cliente_eliminar'),
    path('compra/', CompraCreateView.as_view(), name='compra_crear'),
     path('compralistar/', CompraListView.as_view(), name='compra_listar'),

     path('venta/', VentaCreateView.as_view(), name='venta_crear'),
     path('ventalistar/', VentaListView.as_view(), name='venta_listar'),

 path('reporte/', reportView.as_view(), name='reporte'),
]

web/urls.py
from django.contrib import admin
from django.urls import include, path
# Importamos las dos siguientes lineas para que reconozca la linea 25: Es para la Imagen de Perfil. Ok
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    path('site/', include(('changehouse.urls', 'changehouse'), namespace='site')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Imagen de perfil

changehouse/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.

TIPOPER = (
       ('Natural', 'N'),
       ('Juridica', 'J'),
)

ESTADOS = (('0', 'Activo'), ('1', 'Desactivo'))

TIPOID = (
       ('TI', 'TI'),
       ('CC', 'CC'),
)

CHANGE = (('Dolares a Pesos', 'Dolares a Pesos'), ('Pesos a Dolares','Pesos a Dolares'))

Venta = ('Venta')

Compra = ('Compra')

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tipoid = models.CharField(max_length=1, choices=TIPOID, default="1")
    identificacion = models.IntegerField()
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default=0)
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True, default="profile_image/zx.jpg")

    def __str__(self):
        return self.user.username


class Cliente(models.Model):
    id_cliente = models.AutoField(primary_key=True)
    Cli_Nombre = models.CharField("Nombres", max_length=25)
    Cli_Apellido = models.CharField(max_length=25)
    Cli_TipoID = models.CharField(max_length=2, choices=TIPOID, default="TI")
    Cli_Identificacion = models.IntegerField()
    Cli_Direccion = models.CharField(max_length=50)
    Cli_Telefono = models.CharField(max_length=50)
    Cli_Persona = models.CharField(max_length=10, choices=TIPOPER, default="Natural")
    Cli_Estado = models.CharField(max_length=1, choices=ESTADOS, default="0")
    #Cli_User_ID = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


    def __str__(self):
        return self.Cli_Nombre

class Compra(models.Model):
    id_compra = models.AutoField(primary_key=True)
    Com_tipo = models.CharField(max_length=20, choices=CHANGE, default="Pesos a Dolares")
    Com_Created = models.DateTimeField(default=timezone.now)
    Com_Cliente_ID = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    Com_Precio = models.DecimalField(decimal_places=2, max_digits=10)
    Com_Cantidad = models.CharField(max_length=50)
    Com_Cambista_ID = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.Com_tipo

class Venta(models.Model):
    id_venta = models.AutoField(primary_key=True)
    Ven_Tipo = models.CharField(max_length=20, choices=CHANGE, default="Pesos a Dolares")
    Ven_Created = models.DateTimeField(default=timezone.now)
    Ven_Cliente_ID = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    Ven_Precio = models.DecimalField(decimal_places=2, max_digits=10)
    Ven_Cantidad = models.CharField(max_length=50)
    Ven_Total = models.CharField(max_length=50)
    Ven_Pago = models.CharField(max_length=50)
    Ven_Vuelto = models.CharField(max_length=50)
    Ven_Cambista_ID = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

changehouse/forms.py
from django import forms
from changehouse.models import Cliente, Compra, Venta
from django.forms.utils import flatatt
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from changehouse.models import UserProfile

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'Cli_Nombre',
            'Cli_Apellido',
            'Cli_TipoID',
            'Cli_Identificacion',
            'Cli_Direccion',
            'Cli_Telefono',
            'Cli_Persona',
           # 'Cli_User_ID',
        ]

        labels = {
            'Cli_Apellido': 'Apellidos',
            'Cli_TipoID': 'Tipo de identificacion',
            'Cli_Identificacion': 'Numero de identificacion',
            'Cli_Direccion': 'Direccion',
            'Cli_Telefono': 'Telefono',
            'Cli_Persona': 'Tipo persona',
          #  'Cli_User_ID': 'Cambista',
        }

    widgets  =  {

                'Cli_Nombre': forms.TextInput(attrs={'class':'form-control'}),
                'Cli_Apellido': forms.TextInput(attrs={'class':'form-control'}),
                'Cli_TipoID': forms.Select(attrs={'class':'form-control'}),
                'Cli_Identificacion': forms.NumberInput(attrs={'class':'form-control'}),
    	        'Cli_Direccion': forms.NumberInput(attrs={'class':'form-control'}),
    	        'Cli_Telefono': forms.NumberInput(attrs={'class':'form-control'}),
                'Cli_Persona': forms.Select(attrs={'class':'form-control'}),
               # 'Cli_User_ID': forms.Select(attrs={'class':'form-control'}),

        }

def clean(self, *arg, **kwargs):
    cleaned_data = super(ClienteForm, self).clean(*arg, **kwargs)

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = [
            'Com_Created',
            'Com_tipo',
            'Com_Cliente_ID',
            'Com_Precio',
            'Com_Cantidad',
            'Com_Cambista_ID',
        ]

        labels = {
            'Com_Created': 'Fecha de operacion',
            'Com_tipo': 'Tipo Compra',
            'Com_Cliente_ID': 'Cliente',
            'Com_Precio': 'Precio',
            'Com_Cantidad': 'Cantidad',
            'Com_Cambista_ID': 'Cambista',
        }

    widgets  =  {

                'Com_Created': forms.TextInput(attrs={'class':'form-control'}),
                'Com_tipo': forms.TextInput(attrs={'class':'form-control'}),
                'Com_Cliente_ID': forms.TextInput(attrs={'class':'form-control'}),
                'Com_Precio': forms.Select(attrs={'class':'form-control'}),
                'Com_Cantidad': forms.NumberInput(attrs={'class':'form-control'}),
                'Com_Cambista_ID': forms.TextInput(attrs={'class':'form-control'}),

        }

class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = [
            'Ven_Tipo',
            'Ven_Created',
            'Ven_Cliente_ID',
            'Ven_Precio',
            'Ven_Cantidad',
            'Ven_Total',
            'Ven_Pago',
            'Ven_Vuelto',
            'Ven_Cambista_ID',
        ]

        labels = {
            'Ven_Tipo': 'Tipo Venta',
            'Ven_Created': 'Fecha de Operacion',
            'Ven_Cliente_ID': 'Cliente',
            'Ven_Precio': 'Precio',
            'Ven_Cantidad':'Cantidad',
            'Ven_Total': 'Total',
            'Ven_Pago': 'Pago',
            'Ven_Vuelto': 'Vuelto',
            'Ven_Cambista_ID': 'Cambista',
        }

changehouse/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
#from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.http import HttpResponse
from changehouse.models import Cliente, Compra, Venta
from changehouse.forms import ClienteForm, CompraForm, VentaForm
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import *;
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth import login as auth_login
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


#Vista de Inicio

class HomePageView(LoginRequiredMixin,TemplateView):  
    template_name = "base/base.html"

    # @login_required(login_url='/accounts/login/')
    def get(self, request,*args,**kwargs):
        return render(request, self.template_name,{'tittle': "Administración"})
 
class LoginPageView(TemplateView):
    template_name = "accounts/login.html"

#Vista Login
def login(request):
    if request.user.is_authenticated():
        return redirect('/site')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('/site')
            else:
                return render(request, 'registration/login.html', {'error': 'Usuario no existe'}, content_type='text/html')
        else:
            return render(request, 'registration/login.html', {'error': 'Usuario o contraseña invalidos.'}, content_type='text/html')
    else:
        return render(request, 'registration/login.html', {}, content_type='text/html')






# class MyLoginView(LoginView):
#     template_name = 'registration/login.html'

#     def form_valid(self, form):
#         user = form.get_user()
#         messages.success(self.request, f'Welcome {user}')
#         return super().form_valid(form)



# #Vista Login
# def login(request):
#     if request.user.is_authenticated():
#         return redirect('/site')
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             if user.is_active:
#                 auth_login(request, user)
#                 return HttpResponseRedirect('/site')
#             else:
#                 return render(request, 'registration/login.html', {'error': 'Usuario no existe'}, content_type='text/html')
#         else:
#             return render(request, 'registration/login.html', {'error': 'Usuario o contraseña invalidos.'}, content_type='text/html')
#     else:
#         return render(request, 'registration/login.html', {}, content_type='text/html')



# def register(request):
# 	return render(request, "accounts/register.html")


# Vistar para crear un cliente
class ClienteCreateView(CreateView):
    model = Cliente
    template_name = 'clientes/add_cliente.html'
    form_class = ClienteForm
    redirect_field_name = 'redirect_to'
    success_url = reverse_lazy('site:cliente_listar')

# Vista para listar los clientes
class ClienteListView(ListView):
    template_name = 'clientes/list_cliente.html'
    redirect_field_name = 'redirect_to'
    # Se descomenta la linea de abajo para que funcione el paginado, sin Datables.
    #paginate_by = 5
    def get_queryset(self):
        return Cliente.objects.filter(Cli_Estado=0)

#Vista para editar un Cliente
class ClienteUpdateView(UpdateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'clientes/update_cliente.html'
    success_url = reverse_lazy('site:cliente_listar')

# Vista para eliminar un cliente
class ClienteDeleteView(DeleteView):
    #queryset = Estudiante.objects.update(Es_Estado=1)
    model = Cliente
    template_name = 'clientes/delete_cliente.html'
    success_url = reverse_lazy('site:cliente_listar')
    redirect_field_name = 'redirect_to'


# Vista para hacer una vista detalle
class ClienteDetailView(DetailView):
    model = Cliente
    template_name = 'clientes/show_cliente.html'
    redirect_field_name = 'redirect_to'



# Vista para registrar una Compra
class CompraCreateView(CreateView):
    model = Compra
    template_name = 'compras/add_compra.html'
    form_class = CompraForm
    redirect_field_name = 'redirect_to'
    success_url = reverse_lazy('site:compra_listar')


# Vista para listar las compras
class CompraListView(ListView):
    template_name = 'compras/list_compra.html'
    redirect_field_name = 'redirect_to'
    # Se descomenta la linea de abajo para que funcione el paginado, sin Datables.
    #paginate_by = 5
    def get_queryset(self):
        return Compra.objects.all()


# Vista para registrar una ventas
class VentaCreateView(CreateView):
    model = Venta
    template_name = 'ventas/add_venta.html'
    form_class = VentaForm
    redirect_field_name = 'redirect_to'
    success_url = reverse_lazy('site:compra_listar')

# Vista para listar las ventas
class VentaListView(ListView):
    template_name = 'ventas/list_venta.html'
    redirect_field_name = 'redirect_to'
    # Se descomenta la linea de abajo para que funcione el paginado, sin Datables.
    #paginate_by = 5
    def get_queryset(self):
        return Venta.objects.all()


#  Vista para Generar Reporte PDF
class reportView(TemplateView):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposicion'] = 'attachment; filename=Reporte'

    buffer = BytesIO()
    c = canvas.Canvas(buffer)

    # Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    c.drawString(30,750,'Ing. Duván Mejia Cortes')

    c.setFont('Helvetica', 12)
    c.drawString(30,735,'Report')

    c.setFont('Helvetica-Bold', 12)
    c.drawString(480,750, "25/08/2019")
    c.line(460,747,560,747)

    c.save()
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    # return response

changehouse/templates/base/b_footer.html
{% load staticfiles %}
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.0
  </div>
  <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
  reserved.
</footer>

changehouse/templates/base/b_header.html
{% load staticfiles %}

  <header class="main-header">
    <!-- Logo -->
    <a href="{% url 'site:inicio' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        AdminLTE Design Team
                        <small><i class="fa fa-clock-o"></i> 2 hours</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="/static/dist/img/user2-1s60x160.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Developers
                        <small><i class="fa fa-clock-o"></i> Today</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Sales Department
                        <small><i class="fa fa-clock-o"></i> Yesterday</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <div class="pull-left">
                        <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Reviewers
                        <small><i class="fa fa-clock-o"></i> 2 days</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                      page and may cause design problems
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-red"></i> 5 new members joined
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                    </a>
                  </li>
                  <li>
                    <a href="#">
                      <i class="fa fa-user text-red"></i> You changed your username
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks: style can be found in dropdown.less -->
          <li class="dropdown tasks-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Create a nice theme
                        <small class="pull-right">40%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">40% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Some task I need to do
                        <small class="pull-right">60%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">60% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Make beautiful transitions
                        <small class="pull-right">80%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">80% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="/static/dist/img/user2-1s60x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs">Ing. Duvan Mejia</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="/static/dist/img/user2-1s60x160.jpg" alt="User Image">

                <p>
                  Ing. Duvan Mejia - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

changehouse/templates/base/b_sidebar.html
{% load staticfiles %}
<!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="/static/dist/img/user2-1s60x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Ing. Duvan Mejia</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>

<li><a href="{% url 'site:inicio' %}"><i class="fa fa-home"></i> <span>Inicio</span></a></li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-address-book-o"></i>
            <span>Clientes</span>
            <span class="pull-right-container">
              <span class="label label-primary pull-right">2</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'site:cliente_crear' %}"><i class="fa fa-edit"></i> Registrar un cliente</a></li>
            <li><a href="{% url 'site:cliente_listar' %}"><i class="fa fa-table"></i> Lista de clientes</a></li>
          </ul>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-briefcase"></i>
            <span>Transacciones</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'site:venta_crear' %}"><i class="fa fa-credit-card"></i> Venta</a></li>
            <li><a href="{% url 'site:compra_crear' %}"><i class="fa fa-credit-card"></i> Compra</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-cloud"></i>
            <span>Reporte</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{% url 'site:reporte' %}"><i class="fa fa-file-pdf-o"></i> General</a></li>
            <li><a href="{% url 'site:venta_listar' %}"><i class="fa fa-bar-chart"></i> Reporte Ventas</a></li>
            <li><a href="{% url 'site:compra_listar' %}"><i class="fa fa-bar-chart"></i> Reporte Compra</a></li>
          </ul>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

changehouse/templates/base/error.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <!-- BEGIN content-->
 <div id="content">
   <div class="wrapper">








<pre style="line-height: 1.25; white-space: pre;">

     \          SORRY            /
      \                         /
       \    This page does     /
        ]   not exist yet.    [    ,'|
        ]                     [   /  |
        ]___               ___[ ,'   |
        ]  ]\             /[  [ |:   |
        ]  ] \           / [  [ |:   |
        ]  ]  ]         [  [  [ |:   |
        ]  ]  ]__     __[  [  [ |:   |
        ]  ]  ] ]\ _ /[ [  [  [ |:   |
        ]  ]  ] ] (#) [ [  [  [ :===='
        ]  ]  ]_].nHn.[_[  [  [
        ]  ]  ]  HHHHH. [  [  [
        ]  ] /   `HH("N  \ [  [
        ]__]/     HHH  "  \[__[
        ]         NNN         [
        ]         N/"         [
        ]         N H         [
       /          N            \
      /           q,            \
     /                           \
</pre>


   </div>
 </div>
 <!-- END content-->
  </body>
</html>