changehouse/urls.py
from django.urls import path, include, re_path
from changehouse.views import *
from django.contrib.auth import views as auth_views
from .views import (
    HomePageView,
    ClienteCreateView,
    ClienteListView,
    ClienteUpdateView,
    ClienteDeleteView,
    ClienteDetailView,
    CompraCreateView,
    reportView,
    LoginPageView)
from .import views

urlpatterns = [
    path('', HomePageView.as_view(), name='inicio'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('nuevo/', ClienteCreateView.as_view(), name='cliente_crear'),
    path('listar/', ClienteListView.as_view(), name='cliente_listar'),
    path('mostrar/<int:pk>/', ClienteDetailView.as_view(), name='cliente_mostrar'),
    path('editar/<int:pk>/', ClienteUpdateView.as_view(), name='cliente_editar'),
    path('eliminar/<int:pk>/', ClienteDeleteView.as_view(), name='cliente_eliminar'),
    #url('editar/(?P<pk>\d+)/$', EstudianteUpdate.as_view(), name='estudiante_editar'),
    #re_path(r'editar/(?P<pk>\d+)/$',  ClienteDeleteView.as_view(), name='cliente_eliminar'),
    path('compra/', CompraCreateView.as_view(), name='compra_crear'),
     path('compralistar/', CompraListView.as_view(), name='compra_listar'),

     path('venta/', VentaCreateView.as_view(), name='venta_crear'),
     path('ventalistar/', VentaListView.as_view(), name='venta_listar'),

 path('reporte/', reportView.as_view(), name='reporte'),
]

web/urls.py
from django.contrib import admin
from django.urls import include, path
# Importamos las dos siguientes lineas para que reconozca la linea 25: Es para la Imagen de Perfil. Ok
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    path('site/', include(('changehouse.urls', 'changehouse'), namespace='site')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Imagen de perfil

changehouse/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.

TIPOPER = (
       ('Natural', 'N'),
       ('Juridica', 'J'),
)

ESTADOS = (('0', 'Activo'), ('1', 'Desactivo'))

TIPOID = (
       ('TI', 'TI'),
       ('CC', 'CC'),
)

CHANGE = (('Dolares a Pesos', 'Dolares a Pesos'), ('Pesos a Dolares','Pesos a Dolares'))

Venta = ('Venta')

Compra = ('Compra')

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tipoid = models.CharField(max_length=1, choices=TIPOID, default="1")
    identificacion = models.IntegerField()
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default=0)
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True, default="profile_image/zx.jpg")

    def __str__(self):
        return self.user.username


class Cliente(models.Model):
    id_cliente = models.AutoField(primary_key=True)
    Cli_Nombre = models.CharField("Nombres", max_length=25)
    Cli_Apellido = models.CharField(max_length=25)
    Cli_TipoID = models.CharField(max_length=2, choices=TIPOID, default="TI")
    Cli_Identificacion = models.IntegerField()
    Cli_Direccion = models.CharField(max_length=50)
    Cli_Telefono = models.CharField(max_length=50)
    Cli_Persona = models.CharField(max_length=10, choices=TIPOPER, default="Natural")
    Cli_Estado = models.CharField(max_length=1, choices=ESTADOS, default="0")
    #Cli_User_ID = models.ForeignKey(UserProfile, on_delete=models.CASCADE)


    def __str__(self):
        return self.Cli_Nombre

class Compra(models.Model):
    id_compra = models.AutoField(primary_key=True)
    Com_tipo = models.CharField(max_length=20, choices=CHANGE, default="Pesos a Dolares")
    Com_Created = models.DateTimeField(default=timezone.now)
    Com_Cliente_ID = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    Com_Precio = models.DecimalField(decimal_places=2, max_digits=10)
    Com_Cantidad = models.CharField(max_length=50)
    Com_Cambista_ID = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.Com_tipo

class Venta(models.Model):
    id_venta = models.AutoField(primary_key=True)
    Ven_Tipo = models.CharField(max_length=20, choices=CHANGE, default="Pesos a Dolares")
    Ven_Created = models.DateTimeField(default=timezone.now)
    Ven_Cliente_ID = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    Ven_Precio = models.DecimalField(decimal_places=2, max_digits=10)
    Ven_Cantidad = models.CharField(max_length=50)
    Ven_Total = models.CharField(max_length=50)
    Ven_Pago = models.CharField(max_length=50)
    Ven_Vuelto = models.CharField(max_length=50)
    Ven_Cambista_ID = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

changehouse/forms.py
from django import forms
from changehouse.models import Cliente, Compra, Venta
from django.forms.utils import flatatt
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from changehouse.models import UserProfile

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'Cli_Nombre',
            'Cli_Apellido',
            'Cli_TipoID',
            'Cli_Identificacion',
            'Cli_Direccion',
            'Cli_Telefono',
            'Cli_Persona',
           # 'Cli_User_ID',
        ]

        labels = {
            'Cli_Apellido': 'Apellidos',
            'Cli_TipoID': 'Tipo de identificacion',
            'Cli_Identificacion': 'Numero de identificacion',
            'Cli_Direccion': 'Direccion',
            'Cli_Telefono': 'Telefono',
            'Cli_Persona': 'Tipo persona',
          #  'Cli_User_ID': 'Cambista',
        }

    widgets  =  {

                'Cli_Nombre': forms.TextInput(attrs={'class':'form-control'}),
                'Cli_Apellido': forms.TextInput(attrs={'class':'form-control'}),
                'Cli_TipoID': forms.Select(attrs={'class':'form-control'}),
                'Cli_Identificacion': forms.NumberInput(attrs={'class':'form-control'}),
    	        'Cli_Direccion': forms.NumberInput(attrs={'class':'form-control'}),
    	        'Cli_Telefono': forms.NumberInput(attrs={'class':'form-control'}),
                'Cli_Persona': forms.Select(attrs={'class':'form-control'}),
               # 'Cli_User_ID': forms.Select(attrs={'class':'form-control'}),

        }

def clean(self, *arg, **kwargs):
    cleaned_data = super(ClienteForm, self).clean(*arg, **kwargs)

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = [
            'Com_Created',
            'Com_tipo',
            'Com_Cliente_ID',
            'Com_Precio',
            'Com_Cantidad',
            'Com_Cambista_ID',
        ]

        labels = {
            'Com_Created': 'Fecha de operacion',
            'Com_tipo': 'Tipo Compra',
            'Com_Cliente_ID': 'Cliente',
            'Com_Precio': 'Precio',
            'Com_Cantidad': 'Cantidad',
            'Com_Cambista_ID': 'Cambista',
        }

    widgets  =  {

                'Com_Created': forms.TextInput(attrs={'class':'form-control'}),
                'Com_tipo': forms.TextInput(attrs={'class':'form-control'}),
                'Com_Cliente_ID': forms.TextInput(attrs={'class':'form-control'}),
                'Com_Precio': forms.Select(attrs={'class':'form-control'}),
                'Com_Cantidad': forms.NumberInput(attrs={'class':'form-control'}),
                'Com_Cambista_ID': forms.TextInput(attrs={'class':'form-control'}),

        }

class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = [
            'Ven_Tipo',
            'Ven_Created',
            'Ven_Cliente_ID',
            'Ven_Precio',
            'Ven_Cantidad',
            'Ven_Total',
            'Ven_Pago',
            'Ven_Vuelto',
            'Ven_Cambista_ID',
        ]

        labels = {
            'Ven_Tipo': 'Tipo Venta',
            'Ven_Created': 'Fecha de Operacion',
            'Ven_Cliente_ID': 'Cliente',
            'Ven_Precio': 'Precio',
            'Ven_Cantidad':'Cantidad',
            'Ven_Total': 'Total',
            'Ven_Pago': 'Pago',
            'Ven_Vuelto': 'Vuelto',
            'Ven_Cambista_ID': 'Cambista',
        }

changehouse/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
#from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.http import HttpResponse
from changehouse.models import Cliente, Compra, Venta
from changehouse.forms import ClienteForm, CompraForm, VentaForm
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import *;
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth import login as auth_login
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


#Vista de Inicio

class HomePageView(LoginRequiredMixin,TemplateView):  
    template_name = "base/base.html"

    # @login_required(login_url='/accounts/login/')
    def get(self, request,*args,**kwargs):
        return render(request, self.template_name,{'tittle': "Administración"})
 
class LoginPageView(TemplateView):
    template_name = "accounts/login.html"

#Vista Login
def login(request):
    if request.user.is_authenticated():
        return redirect('/site')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return HttpResponseRedirect('/site')
            else:
                return render(request, 'registration/login.html', {'error': 'Usuario no existe'}, content_type='text/html')
        else:
            return render(request, 'registration/login.html', {'error': 'Usuario o contraseña invalidos.'}, content_type='text/html')
    else:
        return render(request, 'registration/login.html', {}, content_type='text/html')






# class MyLoginView(LoginView):
#     template_name = 'registration/login.html'

#     def form_valid(self, form):
#         user = form.get_user()
#         messages.success(self.request, f'Welcome {user}')
#         return super().form_valid(form)



# #Vista Login
# def login(request):
#     if request.user.is_authenticated():
#         return redirect('/site')
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             if user.is_active:
#                 auth_login(request, user)
#                 return HttpResponseRedirect('/site')
#             else:
#                 return render(request, 'registration/login.html', {'error': 'Usuario no existe'}, content_type='text/html')
#         else:
#             return render(request, 'registration/login.html', {'error': 'Usuario o contraseña invalidos.'}, content_type='text/html')
#     else:
#         return render(request, 'registration/login.html', {}, content_type='text/html')



# def register(request):
# 	return render(request, "accounts/register.html")


# Vistar para crear un cliente
class ClienteCreateView(CreateView):
    model = Cliente
    template_name = 'clientes/add_cliente.html'
    form_class = ClienteForm
    redirect_field_name = 'redirect_to'
    success_url = reverse_lazy('site:cliente_listar')

# Vista para listar los clientes
class ClienteListView(ListView):
    template_name = 'clientes/list_cliente.html'
    redirect_field_name = 'redirect_to'
    # Se descomenta la linea de abajo para que funcione el paginado, sin Datables.
    #paginate_by = 5
    def get_queryset(self):
        return Cliente.objects.filter(Cli_Estado=0)

#Vista para editar un Cliente
class ClienteUpdateView(UpdateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'clientes/update_cliente.html'
    success_url = reverse_lazy('site:cliente_listar')

# Vista para eliminar un cliente
class ClienteDeleteView(DeleteView):
    #queryset = Estudiante.objects.update(Es_Estado=1)
    model = Cliente
    template_name = 'clientes/delete_cliente.html'
    success_url = reverse_lazy('site:cliente_listar')
    redirect_field_name = 'redirect_to'


# Vista para hacer una vista detalle
class ClienteDetailView(DetailView):
    model = Cliente
    template_name = 'clientes/show_cliente.html'
    redirect_field_name = 'redirect_to'



# Vista para registrar una Compra
class CompraCreateView(CreateView):
    model = Compra
    template_name = 'compras/add_compra.html'
    form_class = CompraForm
    redirect_field_name = 'redirect_to'
    success_url = reverse_lazy('site:compra_listar')


# Vista para listar las compras
class CompraListView(ListView):
    template_name = 'compras/list_compra.html'
    redirect_field_name = 'redirect_to'
    # Se descomenta la linea de abajo para que funcione el paginado, sin Datables.
    #paginate_by = 5
    def get_queryset(self):
        return Compra.objects.all()


# Vista para registrar una ventas
class VentaCreateView(CreateView):
    model = Venta
    template_name = 'ventas/add_venta.html'
    form_class = VentaForm
    redirect_field_name = 'redirect_to'
    success_url = reverse_lazy('site:compra_listar')

# Vista para listar las ventas
class VentaListView(ListView):
    template_name = 'ventas/list_venta.html'
    redirect_field_name = 'redirect_to'
    # Se descomenta la linea de abajo para que funcione el paginado, sin Datables.
    #paginate_by = 5
    def get_queryset(self):
        return Venta.objects.all()


#  Vista para Generar Reporte PDF
class reportView(TemplateView):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposicion'] = 'attachment; filename=Reporte'

    buffer = BytesIO()
    c = canvas.Canvas(buffer)

    # Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    c.drawString(30,750,'Ing. Duván Mejia Cortes')

    c.setFont('Helvetica', 12)
    c.drawString(30,735,'Report')

    c.setFont('Helvetica-Bold', 12)
    c.drawString(480,750, "25/08/2019")
    c.line(460,747,560,747)

    c.save()
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    # return response

changehouse/templates/compras/list_cliente.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Administracion</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{% static 'bower_components/morris.js/morris.css' %}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{% static 'bower_components/jvectormap/jquery-jvectormap.css' %}">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

{% include "base/b_header.html" %}
  <!-- Left side column. contains the logo and sidebar -->
  {% include "base/b_sidebar.html" %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Small boxes (Stat box) -->
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Registro de clientes:</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">
          {% block content %}


          <table class="table table-bordered" id="cliente">
          	<thead>
          		<tr>
          			<td>#</td>
          			<td>Nombres</td>
          			<td>Apellidos</td>
          			<td>Tipo ID</td>
                <td>Identificacion</td>
          			<td>Direccion</td>
          			<td>Telefono</td>
          			<td>Tipo persona</td>
                <td>Acciones</td>
          		</tr>

          	</thead>
          	<tbody>
          		{% if object_list %}
          		{% for cliente in object_list %}
          		<tr>
          			<td>{{ cliente.id_cliente }}</td>
          			<td>{{ cliente.Cli_Nombre }}</td>
          			<td>{{ cliente.Cli_Apellido }}</td>
                <td>{{ cliente.Cli_TipoID }}</td>
                <td>{{ cliente.Cli_Identificacion }}</td>
          			<td>{{ cliente.Cli_Direccion }}</td>
          			<td>{{ cliente.Cli_Telefono }}</td>
                <td>{{ cliente.Cli_Persona }}</td>
          			<td>
          				<a class="btn btn-primary" href="{% url 'site:cliente_mostrar' cliente.id_cliente %}">Ver</a>
          				<a class="btn btn-primary" href="{% url 'site:cliente_editar' cliente.id_cliente %}">Editar</a>
          				<a class="btn btn-danger" href="{% url 'site:cliente_eliminar' cliente.id_cliente %}">Eliminar</a>
          			</td>
          		</tr>
          		{% endfor %}
          		{% else %}
          		<h1>No hay registros de clientes</h1>
          		{% endif %}
          	</tbody>
          </table>
          <ul class="pager">
          	<li>
          		{% if page_obj.has_previous %}
                 	 <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
          		{% endif %}
                  </li>
          	<li>
          		{% if page_obj.has_next %}
               	 <a href="?page={{ page_obj.next_page_number }}">Next</a>
              	{% endif %}
              </li>
          </ul>
          {% endblock%}
        </div>
        <!-- /.box-body -->
        <div class="box-footer">

        </div>
        <!-- /.box-footer-->
      </div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% include "base/b_footer.html" %}

  <!-- Control Sidebar -->
{% include "base/b_controlsidebar.html" %}
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'bower_components/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="{% static 'bower_components/raphael/raphael.min.js' %}"></script>
<script src="{% static 'bower_components/morris.js/morris.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'bower_components/jquery-sparkline/dist/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'bower_components/jquery-knob/dist/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
<script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<!-- datepicker -->
<script src="{% static 'bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.0/jquery.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" charset="utf-8"></script>
<script>
$(document).ready( function () {
  $('#estudiantes').DataTable();
} );
</script>
</body>
</html>